### ISSUE TITLE
TypeError: Cannot convert -0.05 to EagerTensor of dtype int32

### ISSUE THREAD

**Issue by SkyisjustTheBeginning** [minimaxir/char-embeddings#6]
@minimaxir I am trying to do text classification with spam messages.

While running the code provided by @minimaxir (with some slight modifications) , I faced this error - 

`TypeError: Cannot convert -0.05 to EagerTensor of dtype int32`

Here is my code - 

`
from __future__ import print_function
from keras.models import Sequential, Model, load_model
from keras.layers import Dense, Activation, Embedding
from keras.layers import LSTM, Input
from keras.optimizers import RMSprop, Adam
from keras.utils.data_utils import get_file
from tensorflow.keras.layers import BatchNormalization
from keras.callbacks import Callback, ModelCheckpoint
from sklearn.decomposition import PCA
import numpy as np
import random
import sys
import csv
import os
import h5py
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.snowball import PorterStemmer
from sklearn import preprocessing
def preprocess_text(sen):
    # Remove punctuations and numbers
    sentence = re.sub('[^a-zA-Z]', ' ', sen)

    # Single character removal
    sentence = re.sub(r"\s+[a-zA-Z]\s+", ' ', sentence)

    # Removing multiple spaces
    sentence = re.sub(r'\s+', ' ', sentence)

    stops = stopwords.words('english')
    #print(stops)
    porter = PorterStemmer()
    for word in sentence.split():
        if word in stops:
            sentence = sentence.replace(word, '')
        sentence = sentence.replace(word, porter.stem(word))
    return sentence.lower()
maxlen = 40  # must match length which generated model
num_char_generated = 30000
df = pd.read_csv('spam.csv')
df['Message'] = df['Message'].apply(preprocess_text)
df.head(10)
mes = []
for i in df['Message']:
    mes.append(i.split())
for m in mes:
    chars = sorted(list(set(m)))
    char_indices = dict((c, i) for i, c in enumerate(chars))
    indices_char = dict((i, c) for i, c in enumerate(chars))

    def sample(preds, temperature=1.0):
    # helper function to sample an index from a probability array
       preds = np.asarray(preds).astype('float64')
       preds = np.log(preds + 1e-6) / temperature
       exp_preds = np.exp(preds)
       preds = exp_preds / np.sum(exp_preds)
       probas = np.random.multinomial(1, preds, 1)
       return np.argmax(probas)

    print('Loading model...')
    model = load_model('model.hdf5')
    f2 = open('text_sample.txt', 'w')

    start_index = random.randint(0, len(text) - maxlen - 1)
    print("He")
    for diversity in [0.2, 0.5, 1.0, 1.2]:
        print()
        print('----- diversity:', diversity)
        f2.write('----- diversity:' + ' ' + str(diversity) + '\n')

        generated = ''
        sentence = text[start_index: start_index + maxlen]
        generated += sentence
        print('----- Generating with seed: "' + sentence + '"')
        f2.write('----- Generating with seed: "' + sentence + '"' + '\n---\n')
        sys.stdout.write(generated)

        for i in range(num_char_generated):
            x = np.zeros((1, maxlen), dtype=np.int)
            for t, char in enumerate(sentence):
              x[0, t] = char_indices[char]

            preds = model.predict(x, verbose=0)[0][0]
            next_index = sample(preds, diversity)
            next_char = indices_char[next_index]
            generated += next_char
            sentence = sentence[1:] + next_char

            sys.stdout.write(next_char)
            sys.stdout.flush()
    f2.write(generated + '\n')
    print("H")
    f2.close()
`

**Comment by find-fun** [comment]
你好，已收到你的邮件，我会尽快处理，谢谢~

**Comment by SkyisjustTheBeginning** [comment]
I'm sorry , Who are you ?

**Comment by SkyisjustTheBeginning** [comment]
謝謝
